### PR TITLE
Add Entity, Repository and Migration for Course table

### LINKED ISSUE #30: FEATURE: Add Course.java entity class
Part of Epic #6
Part of feature #11

Create an entity file for the Course class as defined in #11

### PR DESCRIPTION
**Pull request by r0ckwav3**
## Overview
In this PR I add an entity file, repository and database migration for the Course database table. The database schema is described in #11.

## Validation
To test this change:
 1. go to the dokku and access database happycows-dev-r0ckwav3-db via `dokku postgres:connect`
 2. verify that the table exists with `\dt`
 3. verify that the columns are correct with `\d courses`

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #30

### CODE REVIEW

**Review by AjayLiu — APPROVED** [review]
Looks good!

**Review by pconrad — CHANGES_REQUESTED** [review]
We typically merge the repository class and database migration file at the same time, since they all go together to establish the database table.  (See the team01 project for how that works.)

Could you add those ?

**Comment by r0ckwav3** [comment]
> We typically merge the repository class and database migration file at the same time, since they all go together to establish the database table. (See the team01 project for how that works.)
> 
> Could you add those ?

Added both files! The table is also now visible on dokku's postgres.

**Review by justinwu13 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
