### PR TITLE
Fix bug with wealth sorting mishandling commas

### LINKED ISSUE #7: BUG: Fix Leaderboard Sort by Total Wealth
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

We have noticed that the leaderboard incorrectly ranks Farmers when sorting by total wealth, under certain conditions.

### Expected Behavior

Clicking on the "Total Wealth" table column on the leaderboard should sort the Farmers from least to greatest wealth, and clicking it again should sort from greatest to least wealth. 

### Current / Observed Behavior

When a farmer has between $0 and $1000 (non inclusive), we notice that they are inaccurately sorted on the leaderboard.
Screenshot 2024-11-14 at 5 23 57 PM

Sorting from greatest to least should have put the first 2 farmers at the very bottom of the list, instead it puts them at the top.

We see this when sorting from least to greatest:
Screenshot 2024-11-14 at 5 24 17 PM

The farmers with $100 and $199 should have been ranked at the top of the leaderboard for having the least wealth, but they do not appear until the very bottom

### Steps to Reproduce

1. https://happycows.dokku-00.cs.ucsb.edu/
2. Navigate to the Testing Commons
3. Navigate to the leaderboard
4. Sort by Total Wealth

### Discussion

The issue is probably one related to sorting "strings" vs. sorting "numbers", and will involve having to understand internal details of the OurTable component.

Recognize that the OurTable component is used in many places in the application, so you need a solution that doesn't involve putting specific special case code into that component.

### PR DESCRIPTION
**Pull request by justinwu13**
## Overview

In this PR, the table should now handle sorting by total wealth properly. Previously, the table would place values less than $1,000 higher than values greater than $1,000. In addition, a test is added that checks whether sorting is done correctly.

## Screenshots

image
image
Previously, the orders would have been $1,101.10, $10,000.00, $198.73 and $198.73, $10,000.00, $1,101.10 respectively.

## Feedback Request

Please give suggestions on the following:
- The accessor is now just the raw value instead of the formatted one, I don't think that should break anything but I could've missed something.

## Validation

1. Download this branch.
2. Run the project.
3. Visit a commons buy enough cows for a user to have <$1,000 total wealth. 
4. Check the leaderboard. 
5. Sort by wealth in the table, and verify that the users are in the correct order. You may need to login multiple times as different users to have multiple users show up in the table.

Alternatively:
1. Check my dokku deploy here: https://happycows-dev-justinwu13.dokku-10.cs.ucsb.edu/
2. Visit the test commons.
3. Open the leaderboard, sort by wealth in the table, and verify that the users are in the correct order.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #7

### CODE REVIEW

**Review by r0ckwav3 — COMMENTED** [review]
That fix makes a lot of sense, my only worry is that there's no "id" key in the column anymore. Did you remove that intentionally?

**Comment by justinwu13** [comment]
I'm not too sure on what the id is used for, but I figured because the other fields don't have it that it might be redundant. I could readd it just in case, I suppose the redundancy can't hurt

**Review by r0ckwav3 — DISMISSED** [review]
Looks good!

**Comment by justinwu13** [comment]
Removed id from the wealth column again because it appears to be redundant and causes mutation testing to fail

**Review by r0ckwav3 — DISMISSED** [review]
Ok for real this time now that it passes mutation testing (and we figured out what id does).

**Review by pconrad — APPROVED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
This is good... but we should add a test to prevent a regression (i.e. someone else coming behind and undoing your work without realizing they are introducing a new bug.)

The test would look like this:
* Set up fixtures for a bunch of different values in the leaderboard.
* Render the leaderboard
* Find the sort caret and click it
* Verify that the rows are in the correct order

You can look at the tests for OurTable to get an idea of how those tests go.  That's also a good "warmup exercise" for tackling issue #9

https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/issues/9

It will also take this from a 5 point PR to a 10 point PR.

**Comment by justinwu13** [comment]
Added the requested test

**Comment by r0ckwav3** [comment]
For the tests I have two suggestions:
 * The numbers 100, 1000, 1000000 are a bit hard to tell what the "incorrect" ordering is, can we use some numbers like 200000, 9000, 700 or something where it's more clear what the alphabetical ordering would do
 * Keeping around a test where two users have the same amount of money might be useful since I'm not sure what the expected behavior is there

**Review by r0ckwav3 — CHANGES_REQUESTED** [review]
see above comment

**Comment by justinwu13** [comment]
did requested changes. to be honest I'm not even 100% sure about the details of the bug - it's deeper than just using alphabetical order, as $10,000 still shows up as being greater than $9,000, so I'm not sure the suggestion of changing the leading digits even has the intended effect

**Review by r0ckwav3 — APPROVED** [review]
Looks Good!

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
